apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-doc"
  description: "Lorem ipsum"
  annotations:
    github.com/project-slug: kielosz/test-doc
    backstage.io/techdocs-ref: url:https://github.com/kielosz/test-doc
spec:
  type: documentation
  lifecycle: experimental
  owner: "John Smith"
